In [2]:
import numpy as np

my_list = [1,2,3,4]

my_list = my_list * 2

# it will double the array
print(my_list)


[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
import numpy as np

# to make the array to be numpy data type

my_list = np.array([1,2,3,4])

my_list = my_list * 2

# it will double the array
print(my_list)
print(type(my_list))


[2 4 6 8]
<class 'numpy.ndarray'>


In [7]:
# two dimensioanal array
import numpy as np

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)
print(arr2[0,2])

[[1 2 3]
 [4 5 6]]
3


In [ ]:
# A 3D array is like multiple 2D arrays stacked together.

arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr3)

print(arr3[0,0])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
