In [2]:
import numpy as np

my_list = [1,2,3,4]

my_list = my_list * 2

# it will double the array
print(my_list)


[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
import numpy as np

# to make the array to be numpy data type

my_list = np.array([1,2,3,4])

my_list = my_list * 2

# it will double the array
print(my_list)
print(type(my_list))


[2 4 6 8]
<class 'numpy.ndarray'>


In [7]:
# two dimensioanal array
import numpy as np

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)
print(arr2[0,2])

[[1 2 3]
 [4 5 6]]
3


In [ ]:
# A 3D array is like multiple 2D arrays stacked together.

arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr3)

# arr3[array, row, column]
print(arr3[0, 1, 0])
print(arr3[1, 0, 1])

# Combination of element
print(arr3[0,1,1] + arr3[1,1,1])



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
6
12


In [ ]:
# Slicing

import numpy as np

array = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
    [13,14,15,16],
    [13,14,15,16],
    [13,14,15,16]
])

print("\n Selecting some rows \n")

print(array[0:3])

# array[start:stop:step]

# Meaning:

# start → where to begin
# stop → where to stop (not included)
# step → how many positions to jump

print("\n Selecting wanted rows \n")

print(array[0:4:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Selecting wanted rows 

[[ 1  2  3  4]
 [ 9 10 11 12]]
