In [2]:
name = (input("Enter your name: "))
print("Hello", name)

Hello Victoire


In [2]:
# Exercise 1: Basic Data Types

# Create variables
name = "Ushindi Victoire"
age = 21
height = 1.75
is_student = True

# Print variables and their types
print("Name:", name, type(name))
print("Age:", age, type(age))
print("Height:", height, type(height))
print("Is Student:", is_student, type(is_student))

# Operations
print("Age + 5 =", age + 5)
print("Height * 2 =", height * 2)

# String concatenation
message = "My name is " + name
print(message)


Name: Ushindi Victoire <class 'str'>
Age: 21 <class 'int'>
Height: 1.75 <class 'float'>
Is Student: True <class 'bool'>
Age + 5 = 26
Height * 2 = 3.5
My name is Ushindi Victoire


In [3]:
# Exercise 2: Lists

numbers = [45, 23, 67, 12, 89, 34, 56, 78]

# Maximum
print("Maximum:", max(numbers))

# Minimum
print("Minimum:", min(numbers))

# Sum
print("Sum:", sum(numbers))

# Average
average = sum(numbers) / len(numbers)
print("Average:", average)

# Add 100 to the list
numbers.append(100)
print("Updated list:", numbers)

# Sort in descending order
numbers.sort(reverse=True)
print("Sorted descending:", numbers)

# List comprehension (numbers > 50)
greater_than_50 = [num for num in numbers if num > 50]
print("Numbers greater than 50:", greater_than_50)


Maximum: 89
Minimum: 12
Sum: 404
Average: 50.5
Updated list: [45, 23, 67, 12, 89, 34, 56, 78, 100]
Sorted descending: [100, 89, 78, 67, 56, 45, 34, 23, 12]
Numbers greater than 50: [100, 89, 78, 67, 56]


In [4]:
# Exercise 3: Dictionaries

students = {
    "Alice": [80, 85, 90],
    "Bob": [70, 75, 72],
    "Charlie": [88, 92, 85],
    "David": [60, 65, 70],
    "Eva": [95, 90, 93]
}

# Calculate average score for each student
averages = {}

for name, scores in students.items():
    avg = sum(scores) / len(scores)
    averages[name] = avg

print("Average scores:", averages)

# Find student with highest average
best_student = max(averages, key=averages.get)
print("Best student:", best_student)

# Add a new student
students["Frank"] = [78, 80, 82]
print("Updated students:", students)


Average scores: {'Alice': 85.0, 'Bob': 72.33333333333333, 'Charlie': 88.33333333333333, 'David': 65.0, 'Eva': 92.66666666666667}
Best student: Eva
Updated students: {'Alice': [80, 85, 90], 'Bob': [70, 75, 72], 'Charlie': [88, 92, 85], 'David': [60, 65, 70], 'Eva': [95, 90, 93], 'Frank': [78, 80, 82]}


In [5]:
# Exercise 4: Functions

def calculate_statistics(numbers):
    mean = sum(numbers) / len(numbers)

    sorted_numbers = sorted(numbers)
    n = len(numbers)

    # Median calculation
    if n % 2 == 0:
        median = (sorted_numbers[n//2 - 1] + sorted_numbers[n//2]) / 2
    else:
        median = sorted_numbers[n//2]

    maximum = max(numbers)
    minimum = min(numbers)

    return mean, median, maximum, minimum


# Test function
data = [12, 45, 67, 23, 89, 34, 56, 78, 90, 21]
result = calculate_statistics(data)

print("Mean, Median, Max, Min:", result)


Mean, Median, Max, Min: (51.5, 50.5, 90, 12)


In [6]:
# Exercise 5: Loops and Conditionals

number = 7

# 1. Even or Odd
if number % 2 == 0:
    print(number, "is Even")
else:
    print(number, "is Odd")

# 2. Multiplication table
print("Multiplication Table:")
for i in range(1, 11):
    print(number, "x", i, "=", number * i)

# 3. Prime numbers between 1 and 50
print("Prime numbers between 1 and 50:")

for num in range(2, 51):
    is_prime = True

    for i in range(2, num):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(num)


7 is Odd
Multiplication Table:
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70
Prime numbers between 1 and 50:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


In [1]:
# Creation of an array using np.array
import numpy as np

arr = np.array([10, 30, 20])

print(arr)

[10 30 20]


In [ ]:
#  Create a 3×3 array filled with zeros
import numpy as np

arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# Create a 3×3 array filled with ones
import numpy as np

arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# Create a 2×3 matrix
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# Create a 1D array from 1 to 10
import numpy as np

arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# Create a NumPy array from a list of five numbers
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
# Import NumPy and display its version
import numpy as np
print(np.__version__)

2.4.2


In [9]:
# Print the shape of an array
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)


In [10]:
# Create an array and display its datatype
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)

int64


In [11]:
# Element wise operations are the ones dome to each element of the array : [1,2,3] + [4,5,6] = [5,7,9]
# While Scalar Operation is the one done bwn an array with a single element: [1,2,3] + 5 = [6,7,8]
# vectorized computation: is Doing operations on whole arrays at once (no loops).
#  Numpy operation are faster because it was written in c and optimized for sfor speed
# broadcasting : allows operations between arrays of different shapes. : like adding a number to an array

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b
print(result)


[5 7 9]


In [12]:
#  Multiply array by scalar

import numpy as np

a = np.array([1, 2, 3])

result = a * 3
print(result)

[3 6 9]


In [ ]:
# Subtract one array from another
import numpy as np

a = np.array([5, 6, 7])
b = np.array([1, 2, 3])

result = a - b
print(result)


[4 4 4]


In [ ]:
# Element-wise multiplication
import numpy as np

a = np.array([2, 3, 4])
b = np.array([5, 6, 7])

result = a * b
print(result)


[10 18 28]


In [ ]:
# Statical analysis : analise data using numbers like: Ment, Variance, SD
# Variance measures how far numbers are from the mean
# Large variance → Data is spread out
# Small variance → Data is close to mean

# SD is the square root of variance, and it shows how data varies
# Aggregation : combining many values into one value(sum, mean , max)
#  In short Numpy help in data summarization as it provides fast build-in statical functions.




In [15]:
# Calculate sum of elements
import numpy as np

arr = np.array([1, 2, 3, 4])

print(np.sum(arr))

10


In [16]:
# Find mean of array
import numpy as np

arr = np.array([2, 4, 6, 8])

print(np.mean(arr))

5.0


In [18]:
# Find maximum and minimum
import numpy as np

arr = np.array([3,7,1,9])

print(np.max(arr))
print(np.min(arr))

9
1


In [19]:
# Compute standard deviation(np.std)
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.std(arr))

1.4142135623730951


In [20]:
# Calculate variance (np.var)
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.var(arr))

2.0


In [ ]:
#  Rando Number Generation : help to create number that are not predictable
# And this Random number are are important in Simulations : To test real-world situations using different possible value
# What is np.random?= It is a NumPy module used to generate random numbers.
# Simulation in Data Analisis : is using Random data to imitate real-life situation
# 

In [ ]:
import numpy as np
b = np.array([[1, 2, 4, 6, 7, 8],
              [6, 7, 8, 6, 7, 7]])

# Get Dimension
print(b.ndim)

#  Get the shape
print(b.shape)

# Get Size
print(b.itemsize)




2
(2, 6)
8
