In [1]:
import numpy as np

# From a list
arr = np.array([10, 20, 30, 40, 50])
print('1D Array:', arr)
print('Data type:', arr.dtype)

# 2D Array (like a table)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print('\n2D Array:\n', matrix)

# Special arrays
print('\nZeros:\n', np.zeros((3, 3)))
print('\nOnes:\n', np.ones((2, 4)))
print('\nRange:', np.arange(0, 11, 2))
print('Linspace:', np.linspace(0, 1, 6))

1D Array: [10 20 30 40 50]
Data type: int64

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Range: [ 0  2  4  6  8 10]
Linspace: [0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
import numpy as np
print("NumPy version:", np.__version__)


NumPy version: 2.4.2
hello


In [ ]:
name = input("Enter your name")

/home/victoire/Desktop/My-Project/Python/py312-env/bin/python
